In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.__version__

'1.25.0'

In [6]:
#0-D arrays

In [7]:
arr = np.array(34)

In [8]:
arr

array(34)

In [9]:
type(arr)

numpy.ndarray

In [10]:
#1-Darray

In [11]:
arr = np.array([1,2,3,4,5,6])

In [12]:
arr

array([1, 2, 3, 4, 5, 6])

In [13]:
#2-D arrays

In [14]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#3-D arrays

In [17]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [18]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [19]:
type(arr3)

numpy.ndarray

In [20]:
#check dimension array

In [21]:
arr.ndim

1

In [22]:
arr2.ndim

2

In [23]:
arr3.ndim

3

In [24]:
temp_arr = np.array([1,2,3], ndmin=5)

In [25]:
temp_arr

array([[[[[1, 2, 3]]]]])

In [26]:
temp_arr.ndim

5

In [27]:
arr2[0,2]

3

In [28]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr[1:4]

array([2, 3, 4])

In [30]:
arr2[1,1:]

array([5, 6])

In [31]:
l = [i for i in range(1,13)]

In [32]:
arr = np.array(l)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])