In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.2'

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array((1,2,3))

array([1, 2, 3])

In [8]:
np.fromiter((i for i in range(6)), float)

array([0., 1., 2., 3., 4., 5.])

In [9]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
np.empty([4,3], dtype=int)

array([[94873086885878,              0,   210453397549],
       [  193273528368,   231928234034,   206158430292],
       [  249108103223,   219043332146,   210453397562],
       [  197568495665,   236223201331,   386547056695]])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(1,10,2)

array([ 1., 10.])

In [18]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [20]:
np.random.rand(5)

array([0.37046137, 0.40106871, 0.23398441, 0.75312232, 0.56335648])

In [22]:
np.random.randint(5 , size=10)

array([1, 1, 4, 1, 3, 3, 4, 2, 0, 3])

In [23]:
# nitial Placeholders for 2D Array

In [25]:
np.zeros([2,5],dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [27]:
np.ones([3,5], dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [28]:
np.full([2,2], 67, dtype=int)

array([[67, 67],
       [67, 67]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3],[4,5,6]])

In [32]:
arr.size

6

In [33]:
len(arr)

2

In [34]:
arr.shape

(2, 3)

In [35]:
arr.dtype

dtype('int64')

In [36]:
arr.tolist()

[[1, 2, 3], [4, 5, 6]]